name: stadtschreiber
description: "Stadschreiber"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  maplibre_gl: ^0.24.1
  iconify_flutter: ^0.0.7
  provider: ^6.0.0
  flutter_svg: ^2.0.7
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/styles/
    - assets/fonts/
    - assets/data/categories.json
    - assets/icons/

fonts:
  - family: Open Sans Regular
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
  - family: Open Sans Bold
    fonts:
      - asset: assets/fonts/OpenSans-Bold.ttf
  - family: Open Sans Italic
    fonts:
      - asset: assets/fonts/OpenSans-Italic.ttf
  - family: Open Sans Semibold
    fonts:
      - asset: assets/fonts/OpenSans-SemiBold.ttf
