name: stadtschreiber
description: "Stadschreiber"
publish_to: 'none'
version: 0.2.0+4

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  iconify_flutter: ^0.0.7
  provider: ^6.0.0
  flutter_svg: ^2.0.7
  supabase_flutter: ^2.12.0
  flutter_riverpod: ^3.1.0
  url_launcher: ^6.3.2
  maplibre: ^0.3.3+1
  geolocator: ^14.0.2
  polylabel: ^1.0.1
  vector_math: ^2.2.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/styles/
    - assets/fonts/
    - assets/data/categories.json
    - assets/icons/

fonts:
  - family: Open Sans Regular
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
  - family: Open Sans Bold
    fonts:
      - asset: assets/fonts/OpenSans-Bold.ttf
  - family: Open Sans Italic
    fonts:
      - asset: assets/fonts/OpenSans-Italic.ttf
  - family: Open Sans Semibold
    fonts:
      - asset: assets/fonts/OpenSans-SemiBold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

